# Generated by Django 5.2.18 on 2026-10-08 11:03

import django.core.validators
import django.db.models.deletion
import studio.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (URL)')),
                ('category', models.CharField(choices=[('character', 'Персонажи'), ('architecture', 'Архитектура'), ('product', 'Предметная визуализация'), ('interior', 'Интерьеры'), ('game_asset', 'Игровые ассеты'), ('print', 'Модели для 3D-печати')], max_length=20, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='public/portfolio/', verbose_name='Превью')),
                ('model_file', models.FileField(blank=True, help_text='Если загрузить, посетители смогут вращать модель на странице работы.', upload_to='public/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf']), studio.validators.MaxFileSize(30)], verbose_name='3D-модель (.glb / .gltf)')),
                ('software', models.CharField(blank=True, help_text='Blender, ZBrush…', max_length=120, verbose_name='Софт')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'работа',
                'verbose_name_plural': 'портфолио',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=80, verbose_name='Автор')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг (URL)')),
                ('short_description', models.CharField(max_length=220, verbose_name='Краткое описание')),
                ('description', models.TextField(verbose_name='Подробное описание')),
                ('price_from', models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена от, ₽')),
                ('duration', models.CharField(blank=True, help_text='Например: 3–7 дней', max_length=60, verbose_name='Срок')),
                ('image', models.ImageField(blank=True, upload_to='public/services/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('telegram_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Telegram ID')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('budget', models.CharField(blank=True, max_length=60, verbose_name='Бюджет')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Желаемый срок')),
                ('reference_file', models.FileField(blank=True, upload_to='orders/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'zip', 'rar', '7z', 'obj', 'fbx', 'stl', 'glb']), studio.validators.MaxFileSize(20)], verbose_name='Референсы')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('review', 'На согласовании'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('site', 'Сайт'), ('bot', 'Telegram-бот')], default='site', max_length=10, verbose_name='Источник')),
                ('manager_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='studio.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('client', 'Клиент'), ('manager', 'Менеджер')], max_length=10, verbose_name='Отправитель')),
                ('text', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='studio.order')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('telegram_username', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Токен привязки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'профиль',
                'verbose_name_plural': 'профили',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('kind', models.CharField(choices=[('admin_order', 'Менеджеру: новый заказ'), ('admin_message', 'Менеджеру: сообщение клиента'), ('client_status', 'Клиенту: смена статуса'), ('client_message', 'Клиенту: ответ менеджера')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='studio.order')),
            ],
            options={
                'verbose_name': 'уведомление',
                'verbose_name_plural': 'уведомления Telegram',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sent_at', 'attempts'], name='studio_noti_sent_at_eaa2c2_idx')],
            },
        ),
    ]
