# Generated by Django 5.2.18 on 2026-10-08 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['-created_at'], 'verbose_name': 'элемент портфолио', 'verbose_name_plural': 'портфолио'},
        ),
    ]
