# Generated by Django 5.2.18 on 2026-10-08 15:53

import django.core.validators
import studio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_portfolio_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_file',
            field=models.FileField(blank=True, upload_to='orders/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'zip', 'rar', '7z', 'obj', 'fbx', 'stl', 'glb']), studio.validators.MaxFileSize(20), studio.validators.validate_file_content], verbose_name='Референсы'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='model_file',
            field=models.FileField(blank=True, help_text='Если загрузить, посетители смогут вращать модель на странице работы.', upload_to='public/models/', validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf']), studio.validators.MaxFileSize(30), studio.validators.validate_file_content], verbose_name='3D-модель (.glb / .gltf)'),
        ),
    ]
