# Generated by Django 5.2.18 on 2026-10-08 16:25

import django.core.validators
import django.db.models.deletion
import studio.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_validate_upload_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revisions_used',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Запрошено правок'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('admin_order', 'Менеджеру: новый заказ'), ('admin_message', 'Менеджеру: сообщение клиента'), ('client_status', 'Клиенту: смена статуса'), ('client_message', 'Клиенту: ответ менеджера'), ('client_delivery', 'Клиенту: результат готов'), ('admin_event', 'Менеджеру: событие по заказу')], max_length=20),
        ),
        migrations.CreateModel(
            name='OrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Например: Рендеры, версия 1', max_length=120, verbose_name='Название')),
                ('file', models.FileField(upload_to='deliveries/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'pdf', 'zip', 'rar', '7z', 'glb', 'gltf', 'fbx', 'obj', 'stl', 'blend']), studio.validators.MaxFileSize(40), studio.validators.validate_file_content], verbose_name='Файл')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='studio.order')),
            ],
            options={
                'verbose_name': 'результат',
                'verbose_name_plural': 'результаты',
                'ordering': ['created_at'],
            },
        ),
    ]
