# Generated by Django 5.2.18 on 2026-10-08 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_order_deliveries'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Заказ создан'), ('status', 'Смена статуса'), ('message', 'Сообщение'), ('delivery', 'Результат'), ('revision', 'Запрос правок')], max_length=10, verbose_name='Тип')),
                ('text', models.CharField(max_length=255, verbose_name='Описание')),
                ('to_status', models.CharField(blank=True, max_length=20, verbose_name='Новый статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='studio.order')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'история заказа',
                'ordering': ['created_at', 'pk'],
            },
        ),
    ]
